import Head from "next/head";
import RecipeForm from "../../components/Recipe/RecipeForm";

type Props = {};

const New = (props: Props) => {
  return (
    <>
      <Head>
        <title>New | Let&#39;s Feast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <div className="w-full">
          <RecipeForm />
        </div>
      </main>
    </>
  );
};

export default New;
