import { Recipe } from "@prisma/client";
import { GetServerSidePropsContext } from "next";
import { unstable_getServerSession as getServerSession } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Horizontal from "../components/Dividers/Horizontal";
import RecipeMain from "../components/Recipe/RecipeMain";
import client from "../lib/prismadb";
import { authOptions } from "./api/auth/[...nextauth]";

// import { authOptions } from "./api/auth/[...nextauth]"

export default function Home(recipes: any) {
  const { data: session } = useSession();
  // console.log(recipes.toString());
  return (
    <>
      <Head>
        <title>Home | Let&#39;s Feast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="flex flex-col items-center justify-start w-full min-h-full">
          {recipes.recipes.map((item: Recipe, index: number) => {
            return (
              <>
                <RecipeMain recipe={item} key={index} />
                <Horizontal />
              </>
            );
          })}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const session = await getServerSession(context.req, context.res, authOptions);
  // console.log(req, res, context);
  // const session = await getSession({ req: req.req });
  if (!session) {
    console.log("You are not logged in");
  }
  let recipes = await client.recipe.findMany({
    where: {
      authorId: session!.user!.id,
    },
  });
  return {
    props: {
      recipes,
    },
  };
};
