import Head from "next/head";

type Props = {};

const Profile = (props: Props) => {
  return (
    <>
      <Head>
        <title>Profile | Let&#39;s Feast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Your profile will be here</p>
        </div>
      </main>
    </>
  );
};

export default Profile;
